Api technical employee
weroryn330/2021_BD2_S12_RYNKOWSKA pull request #21
Opened 2021-06-12 17:33 UTC by weroryn330

2021-06-12 22:13 UTC, szymon-s commented
Pracownik techniczny nie powinien mieć wpływu tylko na flagę isOpened? Według mnie ustawianie wysokości i nazwy wyciągu jest zbędne w tym przypadku.

2021-06-13 21:37 UTC, Marcin1701 requested changes

2021-06-13 21:37 UTC, Marcin1701 commented on Spring_Backend/src/main/java/polsl/tab/skiresort/api/technical_employee/TechnicalEmployeeApi.java
> +    @PutMapping("{skiLiftId}")
Should be /{skiLiftId} - '/' is missing

2021-06-13 21:37 UTC, Marcin1701 commented on Spring_Backend/src/main/java/polsl/tab/skiresort/api/technical_employee/TechnicalEmployeeApi.java
> +                                                             @RequestBody SkiLiftRequest request
There is no need of passing whole SkiLiftRequest, we only change state true/false. You can do it by id

2021-06-13 21:37 UTC, Marcin1701 commented on Spring_Backend/src/main/java/polsl/tab/skiresort/api/technical_employee/request/SkiLiftRequest.java
> +public class SkiLiftRequest {
This file can be deleted

2021-06-13 21:37 UTC, Marcin1701 commented on Spring_Backend/src/main/java/polsl/tab/skiresort/api/technical_employee/response/SkiLiftResponse.java
> +public class SkiLiftResponse {
We can return response, maybe it will be useful for frontend

2021-06-13 21:37 UTC, Marcin1701 commented on Spring_Backend/src/main/java/polsl/tab/skiresort/api/technical_employee/service/TechnicalEmployeeService.java
> +        skiLift.setName(skiLiftRequest.getName());
There is no need to rename ski lift, technical will only change true/false flag in database

2021-06-13 21:37 UTC, Marcin1701 commented on Spring_Backend/src/main/java/polsl/tab/skiresort/api/technical_employee/service/TechnicalEmployeeService.java
> +        skiLift.setIsOpened(skiLiftRequest.getIsOpened());
Change only this flag as something opposite like open = !open, this will easily change state true/false

2021-06-13 21:45 UTC, Marcin1701 commented
There is also an error in SkiLift entity. The type of isOpen is set as Character whereas it should be Boolean  - to easily change the flag. 
1. Merge changes from main to get latest version of migrations. 
2. Add new migration changing the type of column to Boolean.
3. Correct the type in entity

2021-06-14 10:10 UTC, closed without merging